PTC.Web/Controllers/ImagemController.cs
using Microsoft.AspNetCore.Mvc;
using PTC.Domain.Interfaces.Services;
using PTC.Web.Models.Interfaces.Services;

namespace PTC.WEB.Controllers
{
    public class ImagemController : Controller
    {
        private readonly IImagemService _imagemService;
        private readonly IGeracaoArquivoService _helperService;

        public ImagemController(IImagemService imagemService, IGeracaoArquivoService helperService)
        {
            _imagemService = imagemService;
            _helperService = helperService;
        }

        [HttpGet]
        public IActionResult ExibirImagensVeiculo()
        {
            return PartialView("_ImagensVeiculo");
        }

        [HttpGet]
        public async Task<JsonResult> ObterCaminhosImagensPorIdOperacao(int idOperacao)
        {
            return Json(await _imagemService.ObterImagensVeiculosPorIdOperacao(idOperacao,false));
        }

        [HttpGet]
        public async Task<IActionResult> DownloadImagensPorIdOperacao(int idOperacao)
        {
            try
            {
                var caminhos = await _imagemService.ObterImagensVeiculosPorIdOperacao(idOperacao, true);
                var fileStream = _helperService.GerarImagensArquivoPDF(caminhos);
                return File(fileStream, "application/pdf", "pdf_file_name.pdf");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);        
            }
        }
    }
}

PTC.Web/Controllers/NotificaController.cs
using Microsoft.AspNetCore.Mvc;
using PTC.Application.Dtos;

namespace PTC.WEB.Controllers
{
    public class NotificaController : Controller
    {
        //Retornando notificacoes de status
        public IActionResult RenderizarMensagemStatus([FromQuery]string action, [FromQuery]string controller, string titulo, string mensagem, bool sucesso)
        {
            MensagemViewModel model = new()
            {
                Controller = controller,
                ControllerAction = action,
                StatusSucesso = sucesso,
                Titulo = titulo,
                Mensagem = mensagem,
            };

            return PartialView("_Notificacao", model);
        }

        //Retornando trava p/ deletes
        public IActionResult RenderizarMensagemTrava([FromQuery]string action, [FromQuery]string controller, string titulo, string mensagem, bool trava, int modelId)
        {
            MensagemViewModel model = new()
            {
                Controller = controller,
                ControllerAction = action,
                Titulo = titulo,
                Mensagem = mensagem,
                Trava = trava,
                ModelId = modelId
            };

            return PartialView("_Notificacao", model);
        }
    }
}

PTC.Web/Controllers/OperacaoController.cs
using Microsoft.AspNetCore.Mvc;
using PTC.Domain.Entities;
using PTC.Application.Dtos;
using PTC.Application.Mapper;
using PTC.Domain.Interfaces.Services;
using PTC.WEB.Models.Enums;

namespace PTC.WEB.Controllers
{
    public class OperacaoController : BaseController
    {
        private readonly IVeiculosService _veiculosService;
        private readonly IOperacaoService _operacaoService;
        private readonly IProprietarioService _proprietarioService;

        public OperacaoController(IServiceProvider services) : base(services)
        {
            _veiculosService = (IVeiculosService)GetAppService(typeof(IVeiculosService));
            _operacaoService = (IOperacaoService)GetAppService(typeof(IOperacaoService));
            _proprietarioService = (IProprietarioService)GetAppService(typeof(IProprietarioService));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var lista = await _operacaoService.ObterPorPeriodo(DateTime.Now.AddDays(-90).Date, DateTime.Now.AddDays(1).Date);
            return View(lista.Select(OperacaoMapper.ToViewModel).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            var proprietarios = await _proprietarioService.ObterPorPeriodo(DateTime.Now.AddDays(-90).Date, DateTime.Now.AddDays(1).Date);
            var selectList = proprietarios.ToViewModel();
            return View(selectList);
        }

        [HttpPost]
        public async Task<IActionResult> Inserir(OperacaoViewModel obj)
        {
            var mensagem = await _operacaoService.Inserir(OperacaoMapper.ToDomain(obj, _webHostEnvironment.WebRootPath));

            if (mensagem.ToLower().Contains("sucesso"))
            {
                await ImagemService(EnumPastaArquivoIdentificador.Veiculos, obj.ArquivosImagens, mensagem, obj.CaminhoImagem);
                return Ok(mensagem);
            }

            return BadRequest(mensagem);
        }

        [HttpDelete]
        public async Task<IActionResult> Deletar(int id)
        {
            var operacao = await _operacaoService.ObterPorId(id);
            if (operacao is null) return BadRequest("Você esta tentando deletar uma operação que não existe");

            try
            {
                await _operacaoService.Deletar(operacao); return NoContent();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var operacao = OperacaoMapper.ToViewModel(await _operacaoService.ObterPorId(id));
            var proprietarios = await _proprietarioService.ObterPorPeriodo(DateTime.Now.AddDays(-90).Date, DateTime.Now.AddDays(1).Date);
            operacao.ProprietariosHtmlSelectList.AddRange(proprietarios.ToViewModel().ProprietariosHtmlSelectList);

            return View(operacao);
        }

        [HttpPost]
        public async Task<IActionResult> Alterar(Veiculo obj)
        {
            await _veiculosService.Alterar(obj);
            //await ImagemService(EnumPastaArquivoIdentificador.Veiculos, obj.Imagem, mensagem, obj.CaminhoImagem);
            return RedirectToAction(nameof(Index));
        }


    }
}

PTC.Web/Controllers/ProprietarioController.cs
using Microsoft.AspNetCore.Mvc;
using PTC.Application.Dtos;
using PTC.Application.Mapper;
using PTC.Domain.Interfaces.Services;
using PTC.WEB.Models.Enums;

namespace PTC.WEB.Controllers
{
    public class ProprietarioController : BaseController
    {
        private readonly IProprietarioService _proprietarioService;

        public ProprietarioController(IServiceProvider services) : base(services)
        {
            _proprietarioService = (IProprietarioService)GetAppService(typeof(IProprietarioService));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var proprietarios = await _proprietarioService.ObterPorPeriodo(DateTime.Now.AddDays(-90).Date, DateTime.Now.AddDays(1).Date);
            return View(proprietarios.Select(ProprietarioMapper.ToViewModel).ToList());
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar([FromRoute]int id)
        {
            return View(ProprietarioMapper.ToViewModel(await _proprietarioService.ObterPorId(id)));
        }

        [HttpGet]
        public async Task<IActionResult> FiltroDinamico(string filtro)
        {
            var proprietarios = await _proprietarioService.Filtrar(filtro);
            return View("Index", proprietarios.Select(ProprietarioMapper.ToViewModel).ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Inserir(ProprietarioViewModel proprietario)
        {
            var mensagem = await _proprietarioService.Inserir(ProprietarioMapper.ToDomain(proprietario));

            if (mensagem.ToLower().Contains("sucesso"))
            {
                await ImagemService(EnumPastaArquivoIdentificador.Proprietarios, proprietario.Imagem, mensagem, proprietario.CaminhoImagem);
                return Ok(mensagem);
            }

            return BadRequest(mensagem);
        }

        [HttpDelete]
        public async Task<IActionResult> Deletar([FromRoute] int id)
        {
            try
            {
                var proprietario = await _proprietarioService.ObterPorId(id);
                if (proprietario is null) return BadRequest("Proprietario inexistente");

                await _proprietarioService
                    .Deletar(proprietario);

                return NoContent();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPut]
        public async Task<IActionResult> Alterar([FromForm]ProprietarioViewModel obj)
        {
            var mensagem = await _proprietarioService.Alterar(ProprietarioMapper.ToDomain(obj));

            if (mensagem.ToLower().Contains("sucesso"))
            {
                await ImagemService(EnumPastaArquivoIdentificador.Proprietarios, obj.Imagem, obj.CaminhoImagem);
                return Ok(mensagem);
            }

            return BadRequest(mensagem);
        }

        [HttpGet]
        public async Task<IActionResult> ObterTodos()
        {
            var proprietarios = await _proprietarioService.ObterTodos();
            return Json(proprietarios.Select(ProprietarioMapper.ToViewModel).ToList());
        }

        [HttpGet]
        public async Task<IActionResult> ObterPorPeriodo(DateTime dataInicio, DateTime dataTermino, int pagina = 1)
        {
            var proprietarios = await _proprietarioService.ObterPorPeriodo(dataInicio, dataTermino, pagina);
            return Json(nameof(Index), proprietarios.Select(x => ProprietarioMapper.ToViewModel(x, pagina)).ToList());
        }
    }
}

PTC.Web/Views/Operacao/Adicionar.cshtml
@using PTC.Domain.Enums;
@model PTC.Application.Dtos.OperacaoViewModel

<div class="modal-content">
    <div class="modal-header">
        <h3>
            <span id="headerMarca">Novo Veículo</span>
            <img class="img-logo" src="#" style="display:none" />
        </h3>
    </div>
    <div class="modal-body">
        <partial name="../Operacao/_Formulario.cshtml" />
        <div id="mdlAdicionarMarca" class="modal" role="dialog">
            <partial name="../Marcas/_Adicionar.cshtml" />
        </div>
        <div id="mdlRedirectPessoaForm" class="modal" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header modal-header-align">
                        <span id="btnFecharMdlRedirectPessoaForm" class="close span-close-modal" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </span>
                    </div>
                    <div class="modal-body">
                        <fieldset>
                            <p>Tem certeza que deseja ser redirecionado para a tela de inclusão de proprietário?</p>
                        </fieldset>
                        <hr />
                        <div class="row">
                            <div class="col-12 text-right">
                                <button onclick="RedirecionarFormProprietario()" type="button" class="btn btn-success">Confirmar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="mdlMensagem" class="modal" tabindex="-1" role="dialog"></div>
</div>


@section scripts {
    <script type="text/javascript" src="~/js/Operacao.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#formVeiculo").attr("action", '@Url.Action("Inserir","Operacao")');
            $("#mdlAdicionarMarca").hide();

            factory('POST','@Url.Action("ObterSelectList","Marcas")');
        });

        function RedirecionarFormProprietario() {
            window.location = "@Url.Action("Adicionar","Proprietario")";
        }
    </script>
} 

PTC.Web/Views/Operacao/Editar.cshtml
@model PTC.Application.Dtos.OperacaoViewModel

<div class="modal-content">
    <div class="modal-header">
        <div class="row">
            <div class="col-12" style="text-align:start">
                <h3>
                    @Model.NomeVeiculo
                </h3>
                <sub>
                    <i class="fa fa-calendar-o" aria-hidden="true"></i> Cadastro: @Model.Cadastro
                </sub>
            </div>
        </div>
    </div>
    <div class="modal-body">
        <partial name="../Operacao/_Formulario.cshtml">
    </div>
    <div id="mdlMensagem" class="modal" tabindex="-1" role="dialog"></div>
</div>


@section scripts {
    <script type="text/javascript" src="~/js/Operacao.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            //$("#imgUrl").on('change', function () {
            //    $("#imgLogo").attr($(this).val());
            //});

            $("#formVeiculo").attr('action', '@Url.Action("Alterar","Operacao")');
            factory('PUT', '@Url.Action("ObterSelectList","Marcas")');
            Bind();
        });

        function Bind() {
            var form = []
            var form = document.forms[0];

            debugger;
            $(form.querySelector('input[name="NomeVeiculo"]')).val("@Model.NomeVeiculo");
            $(form.querySelector('input[name="ModeloVeiculo"]')).val("@Model.ModeloVeiculo");
            $(form.querySelector('input[name="Km"]')).val("@Model.Km".replace(",", "."));
            $(form.querySelector('input[name="ValorCompra"]')).val("@Model.ValorCompra".replace(",", "."));
            $(form.querySelector('input[name="ValorTabela"]')).val("@Model.ValorTabela".replace(",", "."));
            $(form.querySelector('input[name="ValorRevenda"]')).val("@Model.ValorRevenda".replace(",", "."));
            $(form.querySelector('input[name="DataFabricacaoVeiculo"]')).val(@Model.DataFabricacaoVeiculo.Date.Year + "-" + @Model.DataFabricacaoVeiculo.Date.Month +"-"+@Model.DataFabricacaoVeiculo.Date.Day);

            if(@Model.MarcaVeiculoId > 0){
                $("#MarcaId").val(@Model.MarcaVeiculoId).change();
            }

            if (@Model.SituacaoAquisicaoId > 0) {
                $("#SituacaoAquisicaoId").val(@Model.SituacaoAquisicaoId).change();
            }
            
            if (@Model.TipoPagamentoAquisicaoId > 0) {
                $("#TipoPagamentoAquisicaoId").val(@Model.TipoPagamentoAquisicaoId).change();
            }

            if (@Model.TipoPagamentoRevendaId > 0) {
                $("#TipoPagamentoRevendaId").val(@Model.TipoPagamentoRevendaId).change();
            }

            if (@Model.ProprietarioId > 0) {
                $("#ProprietarioId").val(@Model.ProprietarioId).change();
            }

            if (@Model.CompradorId > 0) {
                $("#CompradorId").val(@Model.CompradorId).change();
            }
        }
    </script>

}

PTC.Web/Views/Operacao/Index.cshtml
@model IEnumerable<PTC.Application.Dtos.OperacaoViewModel>
<div id="mdlImagens"></div>
<div class="mdlMensagem"></div>
<div class="modalContainner"></div>
<div class="modal-content">
    <div class="modal-body tbl-modal">
        <div class="row">
            <div class="col-6 div-btn-end div-btn-novo" style="text-align:start">
                <a href="@Url.Action("Adicionar","Operacao")" class="btn btn-success btn-novo">
                    Novo
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Codigo<br />Operacao</th>
                    <th>Carro</th>
                    <th>Imagens</th>
                    <th>Proprietario</th>
                    <th>Comprador</th>
                    <th>Cadastro</th>
                    <th>Valor <br /> Compra</th>
                    <th>Valor <br /> Revenda</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (PTC.Application.Dtos.OperacaoViewModel obj in Model)
                {
                    <tr>
                        <td>@obj.Id</td>
                        <td>@obj.NomeVeiculo</td>

                        <td>
                            <button onclick="AbrirModalImagens(@obj.Id)" class="btn btn-sm btn-icon btn-icon-images" type="button" data-target="#mdlImagens" data-toggle="modal">
                                <i class="fa fa-file-image-o" aria-hidden="true"></i>
                            </button>
                            |
                            <button onclick="ExportarImagensPDF(@obj.Id)" class="btn btn-sm btn-icon btn-icon-pdf" type="button">
                                <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                            </button>
                        </td>

                        <td><a href="@Url.Action("Editar", "Proprietario", new { id = obj.ProprietarioId} )" target="_blank">@obj.ProprietarioNome</a></td>
                        <td>
                            @if (string.IsNullOrEmpty(obj.CompradorNome))
                            {
                                @obj.CompradorNome
                            }
                            else
                            {
                                <a href="@Url.Action("Editar", "Proprietario", new { id = obj.CompradorId})" target="_blank">@obj.CompradorNome</a>
                            }
                        </td>
                        <td>@obj.Cadastro</td>
                        <td style="color:blue">@obj.ValorCompraMoedaFormatada</td>


                        @if (obj.ValorRevenda > obj.ValorCompra)
                        {
                            <td style="color:green">@obj.ValorRevendaMoedaFormatada</td>
                        }
                        else
                        {
                            <td style="color:red">@obj.ValorRevendaMoedaFormatada</td>
                        }
                        <td>
                            <a href="@Url.Action("Editar", "Operacao", new { id = obj.Id} )" class="btn btn-sm btn-warning btn-icon">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <span>|</span>
                            <button class="btn btn-sm btn-danger btn-icon" data-id="@System.Text.Json.JsonSerializer.Serialize(obj)">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div id="mdlNotificaDelete" class="modal" tabindex="-1" role="dialog"></div>
</div>


@section scripts {
    <script>
        var objValue = null;
        var objAlterar = null;

        $(document).ready(function() {
            LinkFiltroDinamico();
            EventoFiltro();

            $(".btn-danger").on('click', function(e) {
                e.stopImmediatePropagation();
                objValue = JSON.parse($(this).attr('data-id'));
                travaDelete(objValue.Id);
            });
        });

        function travaDelete(id) {
            $('#mdlNotificaDelete').html('');
            let mensagem = "Cuidado você esta prestes à deletar uma operação, tem certeza que deseja continuar?";
            
            let url = '@Url.Action("RenderizarMensagemTrava","Notifica")' + "?action=" + encodeURI("Deletar") + "&controller=" + encodeURI("Operacao") + "&titulo=" + encodeURI("Cuidado!") + "&mensagem=" + encodeURI(mensagem) + "&trava=" + encodeURI(true) + "&modelId=" + encodeURI(id);
            $('#mdlNotificaDelete').load(url.replace(/amp%3B/g, ""));
            $('#mdlNotificaDelete').modal({ backdrop: 'static', keyboard: true }).show();
        }

        function AbrirModalImagens(id) {
            fetch('@Url.Action("ExibirImagensVeiculo","Imagem")', {
                method: 'GET',
                headers: {
                    accept: 'text/html'
                },
            }).then(function(response) {
                response.text()
                    .then(function(html) {
                        $("#mdlImagens").html(html);
                        CarregarCaminhosImagens(id)
                    })
                    .catch(function(e) {
                        return false;
                    });
            });
        }

        function CarregarCaminhosImagens(teste) {
            fetch('@Url.Action("ObterCaminhosImagensPorIdOperacao","Imagem")' + '?idOperacao=' + parseInt(teste), {
                method: 'GET',
                headers: {
                    accept: 'application/json'
                },
            }).then(function(response) {
                response.json()
                    .then(function(json) {
                        let html = '';

                        for (let i = 0; i < json.length; i++) {
                            html += '<img class="img-fluid card-img" src="' + json[i] + '" width="30" height="40" /> <hr />';
                        }

                        $("#containner-imgs").html(html);
                        $("#mdlImagens").find('.modal').modal('show');
                        $(".modal-backdrop").remove();
                    }).catch(function(message) {
                        ModalMensagem('Falha', message, null, false);
                    });
            });
        }

        function ExportarImagensPDF(idOperacao) {
            fetch('@Url.Action("DownloadImagensPorIdOperacao","Imagem")' + '?idOperacao=' + parseInt(idOperacao), {
                method: 'GET',
                headers: {
                    accept: 'application/pdf'
                },
            }).then(function(response) {
                if (response.status == 400) {
                    response.text().then(function(responseTxt) {
                        debugger;
                        ModalMensagem('Falha', responseTxt, null, false);
                    });
                } else {
                    response.arrayBuffer()
                        .then(function(buffer) {
                            var a = document.createElement("a");
                            var bynaryData = [];
                            bynaryData.push(buffer);
                            a.href = window.URL.createObjectURL(new Blob(bynaryData, { type: "application/pdf" }));
                            a.download = `imagens-op${idOperacao}`;
                            a.click();
                        }).catch(function(errorMessage) {
                            ModalMensagem('Falha', errorMessage, null, false);
                        });
                }
            });
        }
    </script>

}

PTC.Web/Views/Operacao/_Formulario.cshtml
@using PTC.Domain.Enums

<form id="formVeiculo" method="post">
    <div class="form-group" style="text-align:center">
        <div class="row" style="padding-bottom:2%">
            <div class="col-6">
                <div class="col-lg-6 containner-img-upload">
                    <img id="imgVeiculo" class="img-fluid card-img" src="~/images/Veiculos/carrodefault.jpg" alt="Alternate Text" style=" width: auto;" />
                    <input type="file" hidden name="ArquivosImagens" value="" id="inputImg" accept="image/*" class="hide" multiple />
                </div>
                <div class="col-lg-6 containner-btn-img-upload">
                    <button type="button" id="btnImgUpload" class="form-control-file btn btn-info">Upload</button>
                </div>
            </div>
            <div class="col-6 text-left">
                <div class="row" style="padding-bottom:1%">
                    <div class="col-12">
                        <label class="lbl-inputs" for="NomeVeiculo">Nome</label>
                        <input id="NomeVeiculo" type="text" name="NomeVeiculo" value="" class="form-control" required />
                    </div>
                </div>
                <div class="row" style="padding-bottom:1%">
                    <div class="col-12">
                        <label class="lbl-inputs" for="ModeloVeiculo">Modelo</label>
                        <input id="ModeloVeiculo" type="text" name="ModeloVeiculo" value="" class="form-control" required />
                    </div>
                </div>
                <div class="row" style="padding-bottom:1%">
                    <div id="selectMarca" class="col-12"></div>
                </div>
                <div class="row" style="padding-bottom:1%">
                    <div class="col-12">
                        <label class="lbl-inputs" for="Km">Km</label>
                        <input type="number" class="form-control" name="Km" value="" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="padding-bottom:2%">
            <div class="col-4 text-left">
                <label class="lbl-inputs" for="ValorCompra">Valor Compra</label>
                <input type="number" class="form-control" name="ValorCompra" value="" step=".1" />
            </div>
            <div class="col-4 text-left">
                <label class="lbl-inputs" for="ValorTabela">Valor Tabela</label>
                <input type="number" class="form-control" name="ValorTabela" value="" step=".1" />
            </div>
            <div class="col-4 text-left">
                <label class="lbl-inputs" for="ValorRevenda">Valor Revenda</label>
                <input type="number" class="form-control" name="ValorRevenda" value="" step=".1" />
            </div>
        </div>
        <div class="row" style="padding-bottom:2%">
            <div class="col-3 text-left">
                <label class="lbl-inputs" for="EnumSituacaoAquisicao">Situação</label>
                <select name="SituacaoAquisicaoId" class="form-control form-select text-center" asp-items="Html.GetEnumSelectList<EnumSituacaoAquisicao>()"></select>
            </div>
            <div class="col-3 text-left">
                <label class="lbl-inputs" for="fabricacao">Fabricacao</label>
                <input id="fabricacao" type="date" name="DataFabricacaoVeiculo" value="" class="form-control" required />
            </div>
            <div class="col-3 text-left">
                <label class="lbl-inputs" for="EnumTipoPagamentoAquisicao">Forma Pagamento Aquisição</label>
                <select name="TipoPagamentoAquisicaoId" class="form-control form-select text-center" asp-items="Html.GetEnumSelectList<EnumFormaPagamento>()"></select>
            </div>
            <div class="col-3 text-left">
                <label class="lbl-inputs" for="EnumTipoPagamentoAquisicao">Forma Pagamento Revenda</label>
                <select name="TipoPagamentoRevendaId" class="form-control form-select text-center" asp-items="Html.GetEnumSelectList<EnumFormaPagamento>()"></select>
            </div>
        </div>
    </div>
    <div class="row" style="padding-bottom:2%">
        <div class="col-6 text-left">
            <div class="row">
                <div class="col-6 text-left">
                    <label class="lbl-inputs" for="ProprietarioId">Proprietario</label>
                </div>
                <div class="col-6 text-right">
                    <button id="btnAbrirModal" type="button" onclick="AbrirModal('mdlRedirectPessoaForm')" class="btn btn-success btn-sm btnAdicionarMarca">Novo</button>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <select id="ProprietarioId" name="ProprietarioId" asp-items="Model.ProprietariosHtmlSelectList" class="form-control form-select"></select>
                </div>
            </div>
        </div>
        <div class="col-6 text-left">
            <div class="row">
                <div class="col-6 text-left">
                    <label class="lbl-inputs" for="CompradorId">Comprador</label>
                </div>
                <div class="col-6 text-right">
                    <button id="btnAbrirModal" type="button" onclick="AbrirModal('mdlRedirectPessoaForm')" class="btn btn-success btn-sm btnAdicionarMarca">Novo</button>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <select id="CompradorId" name="CompradorId" asp-items="Model.ProprietariosHtmlSelectList" class="form-control form-select col-md-3"></select>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-12 div-btn-end" style="padding-top: 15px;">
            <a class="btn btn-danger" href="@Url.Action("Index","Operacao")">Cancelar</a>
            &nbsp;|&nbsp;
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>
    </div>
</form>